# AWS Secrets Manager Integration using External Secrets Operator (DISABLED)
# Using Terraform-created database-secret instead
# Uncomment and install External Secrets Operator if you want to use AWS Secrets Manager

# apiVersion: external-secrets.io/v1beta1
# kind: SecretStore
# metadata:
#   name: aws-secrets-manager
#   namespace: dev
# spec:
#   provider:
#     aws:
#       service: SecretsManager
#       region: {{ .Values.aws.region }}
#       auth:
#         jwt:
#           serviceAccountRef:
#             name: {{ .Values.serviceAccount.name }}
# ---
# apiVersion: external-secrets.io/v1beta1
# kind: ExternalSecret
# metadata:
#   name: rds-external-secret
#   namespace: dev
# spec:
#   refreshInterval: 1h
#   secretStoreRef:
#     name: aws-secrets-manager
#     kind: SecretStore
#   target:
#     name: rds-secret
#     creationPolicy: Owner
#   data:
#   - secretKey: DATABASE_URI
#     remoteRef:
#       key: {{ .Values.aws.secretName }}
#       property: DATABASE_URI