apiVersion: v1
kind: Secret
metadata:
  name: database-secret
  namespace: dev
type: Opaque
stringData:
  DATABASE_URL: "postgresql://ecommerce:{{ .Values.database.password }}@{{ .Values.database.host }}:5432/ecommerce_db"